name: Deploy to Minikube

on:
  workflow_run:
    workflows: ["Build and Publish Docker Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted  # 🟢 Runs on your local machine

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set kube context to Minikube
        run: |
          kubectl config use-context minikube

      - name: Deploy to Minikube
        run: |
          kubectl apply -f minifest.yml
