name: Deploy to Minikube

on:
  workflow_run:
    workflows: ["Build and Publish Docker Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    env:
      KUBECONFIG: /home/urooj/.minikube/config/config.json   # Update path if needed

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Ensure Minikube is running
        run: |
          minikube status || minikube start

      - name: Show kubeconfig location
        run: echo "KUBECONFIG=$KUBECONFIG"

      - name: List kubectl contexts
        run: kubectl config get-contexts

      - name: Set kube context to Minikube
        run: kubectl config use-context minikube

      - name: Deploy to Minikube
        run: kubectl apply -f minifest.yml

      - name: Verify pods
        run: kubectl get pods -o wide
